apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260627-224616-84lr7baq8svi-service
spec:
  selector:
    app: enterprise-system-20260627-224616-84lr7baq8svi
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
